repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 6e24ff01ab7d5e64045599b81c4cd34d6a6a7159 # 2.4.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 455151c582ab2375999fa7d13c52f1f6a4dc23b3 # 7.32.1
    hooks:
      - id: eslint
